# Generated by Django 5.0.6 on 2024-11-20 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('stay', 'Stay Fit')], default='lose', max_length=20)),
                ('weight', models.IntegerField(default=0)),
                ('weight_goal', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('date_started', models.DateField(default=django.utils.timezone.now)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
