# Generated by Django 5.0.6 on 2024-11-26 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('stay', 'Stay Fit'), ('add', 'Gain Muscle')], default='lose', max_length=20),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_calories', models.IntegerField(default=0)),
                ('calorie_goal', models.IntegerField(default=0)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
