# Generated by Django 5.0.6 on 2024-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_stats_goal_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='old_protein',
            field=models.IntegerField(default=0),
        ),
    ]
