# Generated by Django 5.0.6 on 2024-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_food_old_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='protein_goal',
            field=models.IntegerField(default=0),
        ),
    ]
