# Generated by Django 5.0.6 on 2024-11-29 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_food_protein_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.JSONField(default={})),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
