# Generated by Django 5.0.6 on 2024-11-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='days',
            field=models.JSONField(default=[]),
        ),
    ]
