# Generated by Django 5.0.6 on 2024-12-02 15:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_goal_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('date_started', models.DateField(default=datetime.datetime(2024, 12, 2, 15, 32, 3, 30748, tzinfo=datetime.timezone.utc))),
                ('time_started', models.TimeField(default=datetime.datetime(2024, 12, 2, 15, 32, 3, 30748, tzinfo=datetime.timezone.utc))),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
