# Generated by Django 5.0.6 on 2024-12-02 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='time_started',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
