# Generated by Django 5.0.6 on 2024-12-16 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_activity_log_date_started_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(default='', max_length=20)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('date_eaten', models.DateField(default=django.utils.timezone.now)),
                ('time_eaten', models.TimeField(default=django.utils.timezone.now)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaten_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
