# Generated by Django 5.0.6 on 2024-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_stats_goal_stats_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='weights',
            field=models.JSONField(default=[]),
        ),
    ]
