# Generated by Django 5.1.4 on 2025-01-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_stats_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='starting_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='goal',
            name='workout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stats',
            name='goals',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stats',
            name='weights',
            field=models.JSONField(default=list),
        ),
    ]
